const columns = {
    "one-fifth": "20%",
    "one-quarter": "25%",
    "one-third": "33.33%",
    "two-fifths": "40%",
    "half": "50%",
    "three-fifths": "60%",
    "two-thirds": "66.66%",
    "three-quarters": "75%",
    "four-fifths": "80%",
    "full": "100%",
};

export default {
    styles: {
        ".{{prefix}}alert": {
            alignItems: "center",
            backgroundColor: "primary",
            borderRadius: "0.5rem",
            color: "white",
            display: "flex",
            fontWeight: "bold",
            marginBottom: "1rem",
            marginTop: "0px",
            minWidth: "0px",
            padding: "1.25rem",
            position: "relative",
            variants: "alerts",
        },
        ".{{prefix}}badge": {
            borderRadius: "0.25rem",
            display: "inline-block",
            fontSize: "0.75rem",
            fontWeight: "bold",
            lineHeight: "1.25rem",
            padding: ["0.25rem", "0.5rem"],
            textDecoration: "none",
            verticalAlign: "text-top",
            variants: "badges",
        },
        ".{{prefix}}button": {
            appearance: "none",
            backgroundColor: "primary",
            border: "0px",
            borderRadius: "0.5rem",
            color: "white",
            cursor: "pointer",
            display: "inline-block",
            fontFamily: "inherit",
            fontSize: "inherit",
            fontWeight: "bold",
            lineHeight: "inherit",
            minWidth: "0px",
            padding: ["0.75rem", "1.5rem"],
            textAlign: "center",
            textDecoration: "none",
            userSelect: "none",
            verticalAlign: "middle",
            "&:hover": {
                textDecoration: "none",
                transitionDuration: "0.3s",
                transitionProperty: "background-color",
            },
            variants: "buttons",
        },
        ".{{prefix}}card": {
            backgroundColor: "white",
            borderRadius: "0.5rem",
            color: "inherit",
            display: "block",
            padding: "2rem",
            textDecoration: ["none", "!important"],
            width: "100%",
            variants: "cards",
        },
        ".{{prefix}}checkbox": {
            appearance: "none",
            backgroundColor: "fill",
            borderRadius: "0.25rem",
            boxSizing: "border-box",
            color: "white",
            cursor: "pointer",
            display: "inline-block",
            height: "1.125rem",
            margin: "0.1875rem",
            position: "relative",
            width: "1.125rem",
            verticalAlign: "top",
            "&:after": {
                backgroundColor: "transparent",
                content: "''",
                height: "0.375rem",
                position: "absolute",
            },
            "&:checked,&:indeterminate": {
                backgroundColor: "primary",
                transitionDuration: "0.3s",
                transitionProperty: "background-color",
            },
            "&:indeterminate:after": {
                borderBottomColor: "white",
                borderBottomStyle: "solid",
                borderBottomWidth: "0.125rem",
                left: "0.3125rem",
                top: "0.25rem",
                width: "0.5rem",
            },
            "&:checked:after": {
                borderBottomColor: "white",
                borderBottomStyle: "solid",
                borderBottomWidth: "0.125rem",
                borderLeftColor: "white",
                borderLeftStyle: "solid",
                borderLeftWidth: "0.125rem",
                left: "0.25rem",
                top: "0.3125rem",
                transform: "rotate(-45deg)",
                width: "0.625rem",
            },
            variant: "forms.checkbox",
        },
        ".{{prefix}}close": {
            appearance: "none",
            backgroundColor: "transparent",
            border: "none",
            color: "currentColor",
            cursor: "pointer",
            display: "inline-flex",
            height: "1rem",
            opacity: "0.6",
            position: "relative",
            transition: ["opacity", "0.3s"],
            width: "1rem",
            "&:hover": {
                opacity: "1.0",
            },
            "&:before,&:after": {
                backgroundColor: "currentColor",
                borderRadius: "1px",
                content: "''",
                height: "3px",
                left: "0px",
                position: "absolute",
                top: "6px",
                width: "1rem",
            },
            "&:before": {
                transform: "rotate(45deg)",
            },
            "&:after": {
                transform: "rotate(-45deg)",
            },
            variant: "buttons.close",
        },
        ".{{prefix}}column": {
            flex: "1",
            minHeight: "0",
            padding: "1rem",
            width: "100%",
            variants: "columns",
        },
        ".{{prefix}}columns": {
            display: "flex",
            flexWrap: "wrap",
            marginLeft: "-1rem",
            marginRight: "-1rem",
        },
        ".{{prefix}}content": {
            display: "block",
            marginLeft: "auto",
            marginRight: "auto",
            maxWidth: "1264px",
            paddingLeft: "1.5rem",
            paddingRight: "1.5rem",
            width: "100%",
            variant: "layout.content",
        },
        ".{{prefix}}divider": {
            backgroundColor: "fill",
            border: "0px",
            display: "block",
            height: "0.125rem",
            padding: "0px",
            "&:not(:first-child)": {
                marginTop: "1rem",
            },
            "&:not(:last-child)": {
                marginBottom: "1rem",
            },
            variant: "layout.divider",
        },
        ".{{prefix}}input": {
            backgroundColor: "fill",
            borderColor: "transparent",
            borderStyle: "solid",
            borderWidth: "0.125rem",
            borderRadius: "0.5rem",
            boxSizing: "border-box",
            color: "inherit",
            display: "block",
            fontFamily: "inherit",
            fontSize: "inherit",
            fontWeight: "normal",
            lineHeight: "inherit",
            margin: "0px",
            minWidth: "0px",
            outline: "0px",
            padding: ["0.625rem", "1rem"],
            // verticalAlign: "top",
            width: "100%",
            "&:focus": {
                borderColor: "primary",
            },
            variant: "forms.input",
        },
        ".{{prefix}}label": {
            alignItems: "center",
            color: "inherit",
            display: "flex",
            fontSize: "1rem",
            fontWeight: "bold",
            minWidth: "0px",
            paddingBottom: "0.25rem",
            paddingTop: "0.25rem",
            width: "100%",
            variant: "forms.label",
        },
        ".{{prefix}}modal": {
            backgroundColor: "white",
            borderRadius: "0.5rem",
            display: "block",
            maxHeight: "90vh",
            maxWidth: "600px",
            overflowY: "auto",
            padding: "2rem",
            width: "100%",
            variant: "dialog.modal",
        },
        ".{{prefix}}navlink": {
            borderRadius: "0.5rem",
            color: "inherit",
            cursor: "pointer",
            display: "block",
            fontWeight: "bold",
            margin: "0px",
            padding: "0.75rem",
            textDecoration: ["none", "!important"],
            userSelect: "none",
            whiteSpace: "nowrap",
            width: "100%",
            "&:hover": {
                color: "primary",
            },
            variant: "links.nav",
        },
        ".{{prefix}}paragraph": {
            display: "block",
            marginBottom: "1rem",
            marginTop: "0px",
            variant: "text.paragraph",
        },
        ".{{prefix}}progress": {
            appearance: "none",
            border: "none",
            borderRadius: "999px",
            color: "primary",
            display: "block",
            height: "0.5rem",
            margin: ["0px", "!important"],
            overflow: "hidden",
            padding: ["0px", "!important"],
            width: "100%",
            "&::-webkit-progress-bar": {
                backgroundColor: "transparent",
            },
            "&::-webkit-progress-value": {
                backgroundColor: "currentColor",
            },
            "&::-moz-progress-bar": {
                backgroundColor: "currentColor",
            },
            variant: "loaders.progress",
        },
        ".{{prefix}}radio": {
            appearance: "none",
            boxSizing: "border-box",
            color: "primary",
            cursor: "pointer",
            display: "inline-block",
            height: "1.25rem",
            margin: "0.125rem",
            position: "relative",
            width: "1.25rem",
            "&:before": {
                borderColor: "fill",
                borderStyle: "solid",
                borderRadius: "100%",
                borderWidth: "0.1875rem",
                content: "''",
                display: "block",
                height: "1.25rem",
                left: "0px",
                position: "absolute",
                top: "0px",
                width: "1.25rem",
            },
            "&:after": {
                backgroundColor: "transparent",
                borderRadius: "999px",
                content: "''",
                display: "block",
                height: "0.5rem",
                left: "0.375rem",
                position: "absolute",
                top: "0.375rem",
                width: "0.5rem",
            },
            "&:hover:after": {
                backgroundColor: "fill",
            },
            "&:checked:after": {
                backgroundColor: ["currentColor", "!important"],
            },
            "&:checked:before": {
                borderColor: ["currentColor", "!important"],
            },
            variant: "forms.radio",
        },
        ".{{prefix}}scrim": {
            alignItems: "center",
            backgroundColor: "rgba(0,0,0,0.5)",
            display: "flex",
            height: "100%",
            justifyContent: "center",
            left: "0px",
            overflowY: "hidden",
            overflowX: "hidden",
            position: "fixed",
            top: "0px",
            width: "100%",
            zIndex: "400",
            variant: "dialog.scrim",
        },
        ".{{prefix}}select": {
            // appearance: "none",
            backgroundColor: "fill",
            borderColor: "transparent",
            borderStyle: "solid",
            borderWidth: "0.125rem",
            borderRadius: "0.5rem",
            boxSizing: "border-box",
            color: "inherit",
            display: "block",
            fontSize: "inherit",
            lineHeight: "inherit",
            margin: "0px",
            minHeight: "3rem",
            minWidth: "0px",
            outline: "0px",
            padding: ["0.625rem", "1rem"],
            // verticalAlign: "top",
            width: "100%",
            "&:focus": {
                borderColor: "primary",
            },
            variant: "forms.select",
        },
        ".{{prefix}}slider": {
            appearance: "none",
            backgroundColor: "fill",
            borderRadius: "1rem",
            color: "primary",
            cursor: "pointer",
            display: "block",
            height: "0.25rem",
            marginBottom: "0.5rem",
            marginTop: "0.5rem",
            minWidth: "0px",
            outline: "none",
            transition: ["opacity", "0.2s"],
            width: "100%",
            "&:-webkit-slider-thumb,&:-moz-range-thumb,&:-ms-thumb": {
                backgroundColor: "currentColor",
                border: "none",
                borderRadius: "999px",
                boxSizing: "border-box",
                height: "1rem",
                width: "1rem",
            },
            "&:-webkit-slider-thumb": {
                appearance: "none",
            },
            "&:-ms-thumb": {
                marginTop: "0px",
            },
            variant: "forms.slider",
        },
        ".{{prefix}}spinner": {
            color: "primary",
            display: "inline-block",
            height: "2rem",
            position: "relative",
            width: "2rem",
            "&:before,&:after": {
                border: ["0.25rem", "solid", "transparent"],
                borderRadius: "100%",
                content: "''",
                display: "block",
                height: "2rem",
                left: "0px",
                position: "absolute",
                top: "0px",
                width: "2rem",
            },
            "&:before": {
                borderColor: "currentColor",
                opacity: "0.2",
            },
            "&:after": {
                animationDuration: "1s",
                animationIterationCount: "infinite",
                animationName: "spinnerAnimation",
                animationTimingFunction: "linear",
                borderTopColor: "currentColor",
            },
            variant: "loaders.spinner",
        },
        "@keyframes spinnerAnimation": {
            from: {
                transform: "rotate(0deg)",
            },
            to: {
                transform: "rotate(359deg)",
            },
        },
        ".{{prefix}}switch": {
            appearance: "none",
            boxSizing: "border-box",
            color: "primary",
            cursor: "pointer",
            display: "inline-block",
            height: "1.25rem",
            position: "relative",
            width: "2rem",
            "&:after": {
                backgroundColor: "white",
                borderRadius: "100%",
                content: "''",
                display: "block",
                height: "0.875rem",
                left: "0.1875rem",
                position: "absolute",
                top: "0.1875rem",
                transition: ["left", "0.3s", "ease"],
                width: "0.875rem",
                zIndex: "2",
            },
            "&:before": {
                backgroundColor: "fill",
                borderRadius: "2rem",
                content: "''",
                display: "block",
                height: "100%",
                left: "0px",
                position: "absolute",
                top: "0px",
                transition: ["background-color", "0.3s", "ease"],
                width: "100%",
                zIndex: "1",
            },
            "&:checked:after": {
                left: "1rem",
            },
            "&:checked:before": {
                backgroundColor: "currentColor",
            },
            variant: "forms.switch",
        },
        ".{{prefix}}textarea": {
            backgroundColor: "fill",
            borderColor: "transparent",
            borderStyle: "solid",
            borderWidth: "0.125rem",
            borderRadius: "0.5rem",
            boxSizing: "border-box",
            color: "inherit",
            display: "block",
            fontFamily: "inherit",
            fontSize: "inherit",
            lineHeight: "inherit",
            margin: "0px",
            minWidth: "0px",
            outline: "0px",
            padding: ["0.625rem", "1rem"],
            resize: "vertical",
            // verticalAlign: "top",
            width: "100%",
            "&:focus": {
                borderColor: "primary",
            },
            variant: "forms.textarea",
        },
        ".{{prefix}}title": {
            display: "block",
            fontSize: "3rem",
            fontWeight: "bold",
            lineHeight: "heading",
            marginBottom: "0.5em",
            padding: "0px",
            "&:not(:first-child)": {
                marginTop: "2rem",
            },
            variant: "text.heading",
        },
        ".{{prefix}}subtitle": {
            display: "block",
            fontSize: "2rem",
            fontWeight: "bold",
            lineHeight: "heading",
            marginBottom: "0.5em",
            padding: "0px",
            variant: "text.heading",
        },
        ".{{prefix}}toggler": {
            appearance: "none",
            backgroundColor: "fill",
            borderColor: "transparent",
            borderRadius: "0.5rem",
            borderStyle: "solid",
            borderWidth: "0.125rem",
            color: "currentColor",
            cursor: "pointer",
            display: "block",
            height: "3rem",
            opacity: "0.8",
            paddingLeft: "0.75rem",
            paddingRight: "0.75rem",
            position: "relative",
            width: "3rem",
            zIndex: "400",
            "&:hover": {
                opacity: "1.0",
            },
            "&:before": {
                borderTop: ["0.25rem", "solid", "currentColor"],
                borderBottom: ["0.25rem", "solid", "currentColor"],
                content: "''",
                height: "1.25rem",
                left: "0.5rem",
                position: "absolute",
                width: "1.75rem",
                top: "0.75rem",
            },
            "&:after": {
                backgroundColor: "currentColor",
                content: "''",
                height: "0.25rem",
                left: "0.5rem",
                position: "absolute",
                width: "1.75rem",
                top: "1.25rem",
            },
            variant: "buttons.toggler",
        },
    },
    variants: {
        alerts: {
            primary: {
                backgroundColor: "primary",
                color: "white",
            },
            secondary: {
                backgroundColor: "primary",
                color: "white",
            },
        },
        badges: {
            primary: {
                backgroundColor: "primary",
                color: "white",
            },
            secondary: {
                backgroundColor: "secondary",
                color: "white",
            },
        },
        buttons: {
            primary: {
                backgroundColor: "primary",
                color: "white",
            },
            secondary: {
                backgroundColor: "secondary",
                color: "white",
            },
            full: {
                display: "block",
                width: "100%",
            },
        },
        columns: {
            ...Object.keys(columns).reduce((prevStyles, column) => ({
                ...prevStyles,
                [column]: {
                    flex: "none",
                    width: columns[column],
                    "@breakpoints": {
                        "&-{{breakpoint}}": {
                            flex: "none",
                            width: columns[column],
                        },
                    },
                },
            }), {}),
            hidden: {
                "display": "none",
                "@breakpoints": {
                    "&-{{breakpoint}}": {
                        "display": "none",
                    }
                },
            },
        },
        loaders: {
            spinner: {
                color: "primary",
            },
        },
    },
};
