export default [
    {
        id: "announcement",
        unicode: 57344,
        added: "v4.0.0",
        keywords: ["announcement", "notice", "bullhorn"],
    },
    {
        id: "arrow-down",
        unicode: 57345,
        added: "v4.0.0",
        keywords: ["arrow", "down"],
    },
    {
        id: "arrow-left",
        unicode: 57346,
        added: "v4.0.0",
        keywords: ["arrow", "left"],
    },
    {
        id: "arrow-right",
        unicode: 57347,
        added: "v4.0.0",
        keywords: ["arrow", "right"],
    },
    {
        id: "arrow-up",
        unicode: 57348,
        added: "v4.0.0",
        keywords: ["arrow", "up"],
    },
    {
        id: "arrows",
        unicode: 57349,
        added: "v4.0.0",
        keywords: ["arrow", "move"],
    },
    {
        id: "box",
        unicode: 57350,
        added: "v4.0.0",
        keywords: ["box", "paper", "container"],
    },
    {
        id: "calendar",
        unicode: 57351,
        added: "v4.0.0",
        keywords: ["calendar", "days", "week", "month", "year", "time"],
    },
    {
        id: "check",
        unicode: 57352,
        added: "v4.0.0",
        keywords: ["check", "mark", "done", "accept"],
    },
    {
        id: "quote",
        unicode: 57353,
        added: "v4.0.0",
        keywords: ["quote", "cite"],
    },
    {
        id: "tasks",
        unicode: 57354,
        added: "v4.0.0",
        keywords: ["tasks", "list", "todo"],
    },
    {
        id: "list-ol",
        unicode: 57355,
        added: "v4.0.0",
        keywords: ["list", "order", "ordered"],
    },
    {
        id: "table",
        unicode: 57356,
        added: "v4.0.0",
        keywords: ["table", "tbody", "thead", "rows", "columns"],
    },
    {
        id: "chevron-down",
        unicode: 57357,
        added: "v4.0.0",
        keywords: ["arrow", "chevron", "down"],
    },
    {
        id: "chevron-left",
        unicode: 57358,
        added: "v4.0.0",
        keywords: ["arrow", "chevron", "left"],
    },
    {
        id: "chevron-right",
        unicode: 57359,
        added: "v4.0.0",
        keywords: ["arrow", "chevron", "right"],
    },
    {
        id: "chevron-up",
        unicode: 57360,
        added: "v4.0.0",
        keywords: ["arrow", "chevron", "up"],
    },
    {
        id: "cloud-download",
        unicode: 57361,
        added: "v4.0.0",
        keywords: ["cloud", "download", "server"],
    },
    {
        id: "cloud-upload",
        unicode: 57362,
        added: "v4.0.0",
        keywords: ["cloud", "upload", "server"],
    },
    {
        id: "cloud",
        unicode: 57363,
        added: "v4.0.0",
        keywords: ["cloud", "server"],
    },
    {
        id: "chart-bar",
        unicode: 57364,
        added: "v4.0.0",
        keywords: ["chart", "bars", "data"],
    },
    {
        id: "cross",
        unicode: 57365,
        added: "v4.0.0",
        keywords: ["cross", "delete", "exit", "cancel", "close"],
    },
    {
        id: "edit",
        unicode: 57366,
        added: "v4.0.0",
        keywords: ["edit", "write", "pen", "pencil"],
    },
    {
        id: "chart-line",
        unicode: 57367,
        added: "v4.0.0",
        keywords: ["chart", "line", "data"],
    },
    {
        id: "exclamation",
        unicode: 57368,
        added: "v4.0.0",
        keywords: ["exclamation", "mark", "warning", "notice"],
    },
    {
        id: "expand",
        unicode: 57369,
        added: "v4.0.0",
        keywords: ["expand", "resize"],
    },
    {
        id: "file-empty",
        unicode: 57370,
        added: "v4.0.0",
        keywords: ["file", "empty", "archive", "blank"],
    },
    {
        id: "file",
        unicode: 57371,
        added: "v4.0.0",
        keywords: ["file", "filesystem", "archive"],
    },
    {
        id: "flask",
        unicode: 57372,
        added: "v4.0.0",
        keywords: ["flask", "experiment", "laboratory", "science"],
    },
    {
        id: "folder",
        unicode: 57373,
        added: "v4.0.0",
        keywords: ["folder", "file", "filesystem", "directory"],
    },
    {
        id: "heart",
        unicode: 57374,
        added: "v4.0.0",
        keywords: ["heart", "love", "favourite"],
    },
    {
        id: "house",
        unicode: 57375,
        added: "v4.0.0",
        keywords: ["home", "house", "building"],
    },
    {
        id: "briefcase",
        unicode: 57376,
        added: "v4.0.0",
        keywords: ["briefcase", "executive", "case", "bag", "documents", "business"],
    },
    {
        id: "info",
        unicode: 57377,
        added: "v4.0.0",
        keywords: ["info", "information"],
    },
    {
        id: "lightbulb",
        unicode: 57378,
        added: "v4.0.0",
        keywords: ["lightbulb", "light", "bulb", "illumination"],
    },
    {
        id: "list-ul",
        unicode: 57379,
        added: "v4.0.0",
        keywords: ["list", "items", "ul"],
    },
    {
        id: "location",
        unicode: 57380,
        added: "v4.0.0",
        keywords: ["location", "position", "mark"],
    },
    {
        id: "lock",
        unicode: 57381,
        added: "v4.0.0",
        keywords: ["lock", "security"],
    },
    {
        id: "bars",
        unicode: 57382,
        added: "v4.0.0",
        keywords: ["menu", "hamburger"],
    },
    {
        id: "trophy",
        unicode: 57383,
        added: "v4.0.0",
        keywords: ["trophy", "price", "cup", "winner"],
    },
    {
        id: "minus",
        unicode: 57384,
        added: "v4.0.0",
        keywords: ["minus", "less"],
    },
    {
        id: "palette",
        unicode: 57385,
        added: "v4.0.0",
        keywords: ["palette", "color", "colour", "colors", "draw", "paint"],
    },
    {
        id: "brush",
        unicode: 57386,
        added: "v4.0.0",
        keywords: ["prush", "paint", "painting"],
    },
    {
        id: "plus",
        unicode: 57387,
        added: "v4.0.0",
        keywords: ["plus", "add", "extra"],
    },
    {
        id: "factory",
        unicode: 57388,
        added: "v4.0.0",
        keywords: ["factory", "industry", "production"],
    },
    {
        id: "cart",
        unicode: 57389,
        added: "v4.0.0",
        keywords: ["cart", "shop", "shopping", "market", "buy"],
    },
    {
        id: "question",
        unicode: 57390,
        added: "v4.0.0",
        keywords: ["question", "mark"],
    },
    {
        id: "redo",
        unicode: 57391,
        added: "v4.0.0",
        keywords: ["redo"],
    },
    {
        id: "resize",
        unicode: 57392,
        added: "v4.0.0",
        keywords: ["resize"],
    },
    {
        id: "search",
        unicode: 57393,
        added: "v4.0.0",
        keywords: ["search", "find", "look", "glass", "loupe"],
    },
    {
        id: "gear",
        unicode: 57394,
        added: "v4.0.0",
        keywords: ["settings", "configuration", "gear"],
    },
    {
        id: "star",
        unicode: 57395,
        added: "v4.0.0",
        keywords: ["star", "favourite"],
    },
    {
        id: "clock",
        unicode: 57396,
        added: "v4.0.0",
        keywords: ["time", "clock", "tic", "hours", "minutes", "seconds"],
    },
    {
        id: "trash",
        unicode: 57397,
        added: "v4.0.0",
        keywords: ["trash", "waste", "delete", "remove"],
    },
    {
        id: "undo",
        unicode: 57398,
        added: "v4.0.0",
        keywords: ["undo", "back", "go-back"],
    },
    {
        id: "unlock",
        unicode: 57399,
        added: "v4.0.0",
        keywords: ["lock", "unclock", "security", "open"],
    },
    {
        id: "user-plus",
        unicode: 57400,
        added: "v4.0.0",
        keywords: ["user", "plus", "add", "new", "create"],
    },
    {
        id: "user-minus",
        unicode: 57401,
        added: "v4.0.0",
        keywords: ["user", "remove", "minus", "delete"],
    },
    {
        id: "user",
        unicode: 57402,
        added: "v4.0.0",
        keywords: ["user", "person"],
    },
    {
        id: "volume-down",
        unicode: 57403,
        added: "v4.0.0",
        keywords: ["volume", "sound", "music"],
    },
    {
        id: "volume-mute",
        unicode: 57404,
        added: "v4.0.0",
        keywords: ["volume", "sound", "music", "silence"],
    },
    {
        id: "volume-up",
        unicode: 57405,
        added: "v4.0.0",
        keywords: ["volume", "sound", "music"],
    },
    {
        id: "search-plus",
        unicode: 57406,
        added: "v4.0.0",
        keywords: ["zoom", "search", "plus"],
    },
    {
        id: "search-minus",
        unicode: 57407,
        added: "v4.0.0",
        keywords: ["zoom", "out", "search", "minus"],
    },
    {
        id: "bell",
        unicode: 57408,
        added: "v4.0.0",
        keywords: ["notification", "alert", "ring", "bell"],
    },
    {
        id: "attachment",
        unicode: 57409,
        added: "v4.0.0",
        keywords: ["attachment", "attach", "file", "clip"],
    },
    {
        id: "folder-open",
        unicode: 57410,
        added: "v4.0.0",
        keywords: ["folder", "directory", "open"],
    },
    {
        id: "copy",
        unicode: 57411,
        added: "v4.0.0",
        keywords: ["copy", "files"],
    },
    {
        id: "paste",
        unicode: 57412,
        added: "v4.0.0",
        keywords: ["paste", "files", "clipboard"],
    },
    {
        id: "clipboard",
        unicode: 57413,
        added: "v4.0.0",
        keywords: ["clipboard", "paste"],
    },
    {
        id: "cut",
        unicode: 57414,
        added: "v4.0.0",
        keywords: ["cut", "scissors", "edit"],
    },
    {
        id: "pen",
        unicode: 57415,
        added: "v4.0.0",
        keywords: ["pen", "edit"],
    },
    {
        id: "archive",
        unicode: 57416,
        added: "v4.0.0",
        keywords: ["archive", "files", "container"],
    },
    {
        id: "book",
        unicode: 57417,
        added: "v4.0.0",
        keywords: ["book", "cover", "pages", "content"],
    },
    {
        id: "layers",
        unicode: 57418,
        added: "v4.0.0",
        keywords: ["layers"],
    },
    {
        id: "file-archive",
        unicode: 57419,
        added: "v4.0.0",
        keywords: ["file", "archive", "compress", "zip"],
    },
    {
        id: "file-image",
        unicode: 57420,
        added: "v4.0.0",
        keywords: ["image", "file", "photo", "picture"],
    },
    {
        id: "envelope",
        unicode: 57421,
        added: "v4.0.0",
        keywords: ["envelope","message","sms","email","mail","inbox","correspondence","post"],
    },
    {
        id: "save",
        unicode: 57422,
        added: "v4.0.0",
        keywords: ["save", "disk"],
    },
    {
        id: "rocket",
        unicode: 57423,
        added: "v4.0.0",
        keywords: ["rocket", "space", "spaceship", "stars"],
    },
    {
        id: "shield",
        unicode: 57424,
        added: "v4.0.0",
        keywords: ["shield", "security"],
    },
    {
        id: "shield-check",
        unicode: 57425,
        added: "v4.0.0",
        keywords: ["shield", "security", "checked"],
    },
    {
        id: "tag",
        unicode: 57426,
        added: "v4.0.0",
        keywords: ["tag", "label"],
    },
    {
        id: "map",
        unicode: 57427,
        added: "v4.0.0",
        keywords: ["map", "location"],
    },
    {
        id: "bookmark",
        unicode: 57428,
        added: "v4.0.0",
        keywords: ["bookmark", "mark", "book"],
    },
    {
        id: "image",
        unicode: 57429,
        added: "v4.0.0",
        keywords: ["image", "img", "picture", "photography"],
    },
    {
        id: "grid",
        unicode: 57430,
        added: "v4.0.0",
        keywords: ["grid", "menu", "apps", "list"],
    },
    {
        id: "presentation",
        unicode: 57431,
        added: "v4.0.0",
        keywords: ["presentation", "slides", "class"],
    },
    {
        id: "align-center",
        unicode: 57432,
        added: "v4.0.0",
        keywords: ["align", "text", "centering", "content"],
    },
    {
        id: "align-left",
        unicode: 57433,
        added: "v4.0.0",
        keywords: ["align", "text", "left", "content"],
    },
    {
        id: "align-right",
        unicode: 57434,
        added: "v4.0.0",
        keywords: ["align", "text", "right", "content"],
    },
    {
        id: "align-justify",
        unicode: 57435,
        added: "v4.0.0",
        keywords: ["align", "text", "right", "content"],
    },
    {
        id: "compress",
        unicode: 57436,
        added: "v4.0.0",
        keywords: ["compress", "arrows"],
    },
    {
        id: "puzzle",
        unicode: 57437,
        added: "v4.0.0",
        keywords: ["puzzle", "piece"],
    },
    {
        id: "bold",
        unicode: 57438,
        added: "v4.0.0",
        keywords: ["bold", "text", "content", "strong"],
    },
    {
        id: "italic",
        unicode: 57439,
        added: "v4.0.0",
        keywords: ["italic", "oblique", "text", "content"],
    },
    {
        id: "underline",
        unicode: 57440,
        added: "v4.0.0",
        keywords: ["underline", "text", "content"],
    },
    {
        id: "erase",
        unicode: 57441,
        added: "v4.0.0",
        keywords: ["erase", "delete", "rubber"],
    },
    {
        id: "link",
        unicode: 57442,
        added: "v4.0.0",
        keywords: ["link", "anchor"],
    },
    {
        id: "shield-cross",
        unicode: 57443,
        added: "v4.0.0",
        keywords: ["shield", "security", "error", "danger"],
    },
    {
        id: "play",
        unicode: 57444,
        added: "v4.0.0",
        keywords: ["play", "resume", "controls"],
    },
    {
        id: "stop",
        unicode: 57445,
        added: "v4.0.0",
        keywords: ["stop", "controls"],
    },
    {
        id: "pause",
        unicode: 57446,
        added: "v4.0.0",
        keywords: ["pause", "controls"],
    },
    {
        id: "credit-card",
        unicode: 57447,
        added: "v4.0.0",
        keywords: ["credit", "card", "money", "pay"],
    },
    {
        id: "wallet",
        unicode: 57448,
        added: "v4.0.0",
        keywords: ["cash", "wallet", "money", "pocket", "coins", "cards"],
    },
    {
        id: "step-backward",
        unicode: 57449,
        added: "v4.0.0",
        keywords: ["step", "backward", "controls", "back", "previous"],
    },
    {
        id: "step-forward",
        unicode: 57450,
        added: "v4.0.0",
        keywords: ["step", "forward", "controls", "next"],
    },
    {
        id: "code",
        unicode: 57451,
        added: "v4.0.0",
        keywords: ["computer", "code", "programming", "develop"],
    },
    {
        id: "money",
        unicode: 57452,
        added: "v4.0.0",
        keywords: ["money", "bill", "payments"],
    },
    {
        id: "sliders",
        unicode: 57453,
        added: "v4.0.0",
        keywords: ["sliders", "settings", "configuration"],
    },
    {
        id: "visible",
        unicode: 57454,
        added: "v4.0.0",
        keywords: ["eye", "visible"],
    },
    {
        id: "hidden",
        unicode: 57455,
        added: "v4.0.0",
        keywords: ["eye", "hidden"],
    },
    {
        id: "print",
        unicode: 57456,
        added: "v4.0.0",
        keywords: ["printer", "printing"],
    },
    {
        id: "ruler",
        unicode: 57457,
        added: "v4.0.0",
        keywords: ["ruler", "rule"],
    },
    {
        id: "desktop",
        unicode: 57458,
        added: "v4.0.0",
        keywords: ["computer", "desktop", "device"],
    },
    {
        id: "laptop",
        unicode: 57459,
        added: "v4.0.0",
        keywords: ["computer", "laptop", "device"],
    },
    {
        id: "mobile",
        unicode: 57460,
        added: "v4.0.0",
        keywords: ["mobile", "device"],
    },
    {
        id: "tablet",
        unicode: 57461,
        added: "v4.0.0",
        keywords: ["tablet", "device"],
    },
    {
        id: "sun",
        unicode: 57462,
        added: "v4.0.0",
        keywords: ["sun", "day", "light"],
    },
    {
        id: "moon",
        unicode: 57463,
        added: "v4.0.0",
        keywords: ["moon", "night", "dark"],
    },
    {
        id: "pointer",
        unicode: 57464,
        added: "v4.0.0",
        keywords: ["mouse", "computer", "desktop"],
    },
    {
        id: "text",
        unicode: 57465,
        added: "v4.0.0",
        keywords: ["text", "editor"],
    },
    {
        id: "circle",
        unicode: 57466,
        added: "v4.0.0",
        keywords: ["geometry", "shape"],
    },
    {
        id: "square",
        unicode: 57467,
        added: "v4.0.0",
        keywords: ["geometry", "shape"],
    },
    {
        id: "diamond",
        unicode: 57468,
        added: "v4.0.0",
        keywords: ["geometry", "shape"],
    },
    {
        id: "clone",
        unicode: 57469,
        added: "v4.0.0",
        keywords: ["clone", "copy"],
    },
    {
        id: "circle-half",
        unicode: 57470,
        added: "v4.0.0",
        keywords: ["circle", "shape", "half"],
    },
    {
        id: "fill",
        unicode: 57471,
        added: "v4.0.0",
        keywords: ["fill", "color", "background", "image"],
    },
    {
        id: "gift",
        unicode: 57472,
        added: "v4.0.0",
        keywords: ["gift", "present"],
    },
    {
        id: "filter",
        unicode: 57473,
        added: "v4.0.0",
        keywords: ["filter"],
    },
    {
        id: "font",
        unicode: 57474,
        added: "v4.0.0",
        keywords: ["font", "text"],
    },
    {
        id: "send-backward",
        unicode: 57475,
        added: "v4.0.0",
        keywords: ["send", "backward", "move", "order"],
    },
    {
        id: "bring-forward",
        unicode: 57476,
        added: "v4.0.0",
        keywords: ["bring", "forward", "move", "order"],
    },
    {
        id: "download",
        unicode: 57477,
        added: "v4.0.0",
        keywords: ["download", "internet", "content"],
    },
    {
        id: "upload",
        unicode: 57478,
        added: "v4.0.0",
        keywords: ["upload", "content", "internet"],
    },
    {
        id: "corner",
        unicode: 57479,
        added: "v4.0.0",
        keywords: ["corner", "frame", "border"],
    },
    {
        id: "external-link",
        unicode: 57480,
        added: "v4.0.0",
        keywords: ["external", "link", "open"],
    },
    {
        id: "camera",
        unicode: 57481,
        added: "v4.0.0",
        keywords: ["camera", "photo", "snapshot"],
    },
    {
        id: "dna",
        unicode: 57482,
        added: "v4.0.0",
        keywords: ["dna", "gene", "genomics"],
    },
    {
        id: "crop",
        unicode: 57483,
        added: "v4.0.0",
        keywords: ["crop", "cut", "edit"],
    },
    {
        id: "server",
        unicode: 57484,
        added: "v4.0.0",
        keywords: ["server", "data", "computer"],
    },
    {
        id: "window",
        unicode: 57485,
        added: "v4.0.0",
        keywords: ["window", "program","application"],
    },
    {
        id: "comment",
        unicode: 57486,
        added: "v4.0.0",
        keywords: ["comment","chat","message"],
    },
    {
        id: "vector",
        unicode: 57487,
        added: "v4.0.0",
        keywords: ["vector","svg","bezier","curve"],
    },
    {
        id: "dashboard",
        unicode: 57488,
        added: "v4.0.0",
        keywords: ["dashboard","panel","admin"],
    },
    {
        id: "keyboard",
        unicode: 57489,
        added: "v4.0.0",
        keywords: ["keyboard","type","text","board"],
    },
    {
        id: "directions",
        unicode: 57490,
        added: "v4.0.0",
        keywords: ["directions","sign","road","map"],
    },
    {
        id: "terminal",
        unicode: 57491,
        added: "v4.0.0",
        keywords: ["terminal","cli","command","line"],
    },
    {
        id: "share",
        unicode: 57492,
        added: "v4.0.0",
        keywords: ["share"],
    },
    {
        id: "inbox",
        unicode: 57493,
        added: "v4.0.0",
        keywords: ["inbox","email"],
    },
    {
        id: "coffee",
        unicode: 57494,
        added: "v4.0.0",
        keywords: ["coffee","mug","drik"],
    },
    {
        id: "backpack",
        unicode: 57495,
        added: "v4.0.0",
        keywords: ["backpack","travel"],
    },
    {
        id: "note",
        unicode: 57496,
        added: "v4.0.0",
        keywords: ["note","sticky"],
    },
    {
        id: "notepad",
        unicode: 57497,
        added: "v4.0.0",
        keywords: ["notepad","notes"],
    },
    {
        id: "shapes",
        unicode: 57498,
        added: "v4.0.0",
        keywords: ["figures","geoms"],
    },
    {
        id: "mouse",
        unicode: 57499,
        added: "v4.0.0",
        keywords: ["mouse","device"],
    },
    {
        id: "ticket",
        unicode: 57500,
        added: "v4.0.0",
        keywords: ["ticket","coupon"],
    },
    {
        id: "discount",
        unicode: 57501,
        added: "v4.0.0",
        keywords: ["discount","shop","coupon"],
    },
    {
        id: "basket",
        unicode: 57502,
        added: "v4.0.0",
        keywords: ["basket","shop","market"],
    },
    {
        id: "tools",
        unicode: 57503,
        added: "v4.0.0",
        keywords: ["tools"],
    },
    {
        id: "thumbtack",
        unicode: 57504,
        added: "v4.0.0",
        keywords: ["pin"],
    },
    {
        id: "siimple",
        unicode: 57505,
        added: "v4.0.0",
        keywords: ["siimple", "logo", "brand"],
    },
    {
        id: "face-laugh",
        unicode: 57506,
        added: "v4.0.0",
        keywords: ["face", "laugh"],
    },
    {
        id: "face-smile",
        unicode: 57507,
        added: "v4.0.0",
        keywords: ["face", "smile"],
    },
    {
        id: "face-sad",
        unicode: 57508,
        added: "v4.0.0",
        keywords: ["face", "sad"],
    },
    {
        id: "face-surprise",
        unicode: 57509,
        added: "v4.0.0",
        keywords: ["face", "surprise"],
    },
    {
        id: "face-meh",
        unicode: 57510,
        added: "v4.0.0",
        keywords: ["face", "meh"],
    },
    {
        id: "face-wink",
        unicode: 57511,
        added: "v4.0.0",
        keywords: ["face", "wink"],
    },
    {
        id: "square-half",
        unicode: 57512,
        added: "v4.0.0",
        keywords: ["square", "shape", "half"],
    },
    {
        id: "square-stroke",
        unicode: 57513,
        added: "v4.0.0",
        keywords: ["square", "shape", "empty", "stroke"],
    },
];
