export const navigation = [
    {"group": "introduction", "url": "/getting-started", "label": "Getting started"},
    {"group": "introduction", "url": "/naming", "label": "Naming methodology"},
    {"group": "introduction", "url": "/responsive", "label": "Responsive"},
    {"group": "introduction", "url": "/packages", "label": "Packages"},
    {"group": "customization", "url": "/configuration", "label": "Configuration"},
    {"group": "customization", "url": "/theme", "label": "Theme"},
    {"group": "customization", "url": "/colors", "label": "Colors"},
    {"group": "customization", "url": "/icons", "label": "Icons"},
    {"group": "customization", "url": "/elements", "label": "Elements"},
    {"group": "customization", "url": "/helpers", "label": "Helpers"},
    {"group": "elements", "url": "/elements/alert", "label": "Alert"},
    {"group": "elements", "url": "/elements/badge", "label": "Badge"},
    {"group": "elements", "url": "/elements/button", "label": "Button"},
    {"group": "elements", "url": "/elements/card", "label": "Card"},
    {"group": "elements", "url": "/elements/checkbox", "label": "Checkbox"},
    {"group": "elements", "url": "/elements/close", "label": "Close"},
    {"group": "elements", "url": "/elements/container", "label": "Container"},
    {"group": "elements", "url": "/elements/column", "label": "Column"},
    {"group": "elements", "url": "/elements/crumb", "label": "Crumb"},
    {"group": "elements", "url": "/elements/divider", "label": "Divider"},
    {"group": "elements", "url": "/elements/input", "label": "Input"},
    {"group": "elements", "url": "/elements/label", "label": "Label"},
    {"group": "elements", "url": "/elements/menu", "label": "Menu"},
    {"group": "elements", "url": "/elements/modal", "label": "Modal"},
    {"group": "elements", "url": "/elements/navlink", "label": "Navlink"},
    {"group": "elements", "url": "/elements/paragraph", "label": "Paragraph"},
    {"group": "elements", "url": "/elements/progress", "label": "Progress"},
    {"group": "elements", "url": "/elements/radio", "label": "Radio"},
    {"group": "elements", "url": "/elements/scrim", "label": "Scrim"},
    {"group": "elements", "url": "/elements/select", "label": "Select"},
    {"group": "elements", "url": "/elements/slider", "label": "Slider"},
    {"group": "elements", "url": "/elements/spinner", "label": "Spinner"},
    {"group": "elements", "url": "/elements/switch", "label": "Switch"},
    {"group": "elements", "url": "/elements/table", "label": "Table"},
    {"group": "elements", "url": "/elements/textarea", "label": "Textarea"},
    {"group": "elements", "url": "/elements/title", "label": "Title"},
    {"group": "helpers", "url": "/helpers/colors", "label": "Colors"},
    {"group": "helpers", "url": "/helpers/opacity", "label": "Opacity"},
    {"group": "helpers", "url": "/helpers/radius", "label": "Radius"},
    {"group": "helpers", "url": "/helpers/shadow", "label": "Shadow"},
    {"group": "helpers", "url": "/helpers/sizing", "label": "Sizing"},
    {"group": "helpers", "url": "/helpers/spacing", "label": "Spacing"},
    {"group": "helpers", "url": "/helpers/typography", "label": "Typography"},
    {"group": "helpers", "url": "/helpers/flexbox", "label": "Flexbox"},
    {"group": "helpers", "url": "/helpers/other", "label": "Other helpers"},
    {"group": "packages", "url": "/packages/core", "label": "@siimple/core"},
    {"group": "packages", "url": "/packages/colors", "label": "@siimple/colors"},
    {"group": "packages", "url": "/packages/theme", "label": "@siimple/theme"},
    {"group": "packages", "url": "/packages/elements", "label": "@siimple/preset-elements"},
    {"group": "packages", "url": "/packages/helpers", "label": "@siimple/preset-helpers"},
    {"group": "packages", "url": "/packages/reboot", "label": "@siimple/preset-reboot"},
    {"group": "packages", "url": "/packages/markup", "label": "@siimple/preset-markup"},
    {"group": "packages", "url": "/packages/icons", "label": "@siimple/preset-icons"},
    {"group": "guides", "url": "/guides/styles", "label": "Styles syntax"},
    {"group": "recipes", "url": "/recipes/features", "label": "Features"},
    {"group": "recipes", "url": "/recipes/footer", "label": "Footer"},
    {"group": "recipes", "url": "/recipes/hero", "label": "Hero"},
    {"group": "recipes", "url": "/recipes/navbar", "label": "Navbar"},
    {"group": "recipes", "url": "/recipes/pricing", "label": "Pricing"},
    {"group": "recipes", "url": "/recipes/sign-in", "label": "Sign in"},
    {"group": "recipes", "url": "/recipes/tabs", "label": "Tabs"},
];
