name: "Icon request"
description: "Request a new icon for siimple"
title: "Icon request: "
labels: ["request-icon"]
asignees: "-"
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: "The title of the issue starts with 'Icon request: ' and is followed by the requested icon name."
          required: true
        - label: "I have [searched](https://github.com/jmjuanes/siimple/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues."
          required: true
        - label: "I have read the [contributing guidelines](https://github.com/jmjuanes/siimple/blob/main/CONTRIBUTING.md)."
          required: true
  
  - type: input
    attributes:
      label: "Icon name"
      description: "Name of the icon you are requesting"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Icon description"
      description: "Please provide a brief description of the icon."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Icon draft"
      description: "Please provide a draft of the icon."
  