export const documentationNav = [
    {"group": "getting-started", "url": "/installation", "label": "Installation"},
    {"group": "getting-started", "url": "/naming", "label": "Naming methodology"},
    {"group": "getting-started", "url": "/responsive", "label": "Responsive"},
    {"group": "getting-started", "url": "/configuration", "label": "Configuration"},
    {"group": "getting-started", "url": "/theme", "label": "Theme"},
    {"group": "getting-started", "url": "/plugins", "label": "Components"},
    {"group": "components", "url": "/components/alert", "label": "Alert"},
    {"group": "components", "url": "/components/badge", "label": "Badge"},
    {"group": "components", "url": "/components/btn", "label": "Button"},
    {"group": "components", "url": "/components/card", "label": "Card"},
    {"group": "components", "url": "/components/checkbox", "label": "Checkbox"},
    {"group": "components", "url": "/components/close", "label": "Close"},
    {"group": "components", "url": "/components/content", "label": "Content"},
    {"group": "components", "url": "/components/column", "label": "Column"},
    {"group": "components", "url": "/components/crumb", "label": "Crumb"},
    {"group": "components", "url": "/components/divider", "label": "Divider"},
    {"group": "components", "url": "/components/input", "label": "Input"},
    {"group": "components", "url": "/components/label", "label": "Label"},
    {"group": "components", "url": "/components/navlink", "label": "NavLink"},
    {"group": "components", "url": "/components/paragraph", "label": "Paragraph"},
    {"group": "components", "url": "/components/quote", "label": "Quote"},
    {"group": "components", "url": "/components/radio", "label": "Radio"},
    {"group": "components", "url": "/components/select", "label": "Select"},
    {"group": "components", "url": "/components/spinner", "label": "Spinner"},
    {"group": "components", "url": "/components/switch", "label": "Switch"},
    {"group": "components", "url": "/components/tab", "label": "Tab"},
    {"group": "components", "url": "/components/table", "label": "Table"},
    {"group": "components", "url": "/components/text", "label": "Text"},
    {"group": "components", "url": "/components/textarea", "label": "Textarea"},
    {"group": "components", "url": "/components/title", "label": "Title"},
    {"group": "experiments", "url": "/experiments/modal", "label": "Modal"},
    {"group": "experiments", "url": "/experiments/progress", "label": "Progress"},
    {"group": "experiments", "url": "/experiments/scrim", "label": "Scrim"},
    {"group": "experiments", "url": "/experiments/slider", "label": "Slider"},
    {"group": "helpers", "url": "/helpers/color", "label": "Color"},
    {"group": "helpers", "url": "/helpers/cursor", "label": "Cursor"},
    {"group": "helpers", "url": "/helpers/display", "label": "Display"},
    {"group": "helpers", "url": "/helpers/flexbox", "label": "Flexbox"},
    {"group": "helpers", "url": "/helpers/opacity", "label": "Opacity"},
    {"group": "helpers", "url": "/helpers/overflow", "label": "Overflow"},
    {"group": "helpers", "url": "/helpers/positioning", "label": "Positioning"},
    {"group": "helpers", "url": "/helpers/radius", "label": "Radius"},
    {"group": "helpers", "url": "/helpers/sizing", "label": "Sizing"},
    {"group": "helpers", "url": "/helpers/spacing", "label": "Spacing"},
    {"group": "helpers", "url": "/helpers/typography", "label": "Typography"},
    {"group": "guides", "url": "/guides/styles", "label": "Styles syntax"},
];
