export const documentationNav = [
    {"group": "getting-started", "url": "/installation", "label": "Installation"},
    {"group": "getting-started", "url": "/usage", "label": "Usage"},
    {"group": "getting-started", "url": "/naming", "label": "Naming methodology"},
    {"group": "getting-started", "url": "/responsive", "label": "Responsive"},
    {"group": "customize", "url": "/configuration", "label": "Configuration"},
    {"group": "customize", "url": "/scales", "label": "Theme Scales"},
    {"group": "customize", "url": "/variants", "label": "Variants"},
    {"group": "customize", "url": "/colors", "label": "Colors"},
    {"group": "elements", "url": "/elements/alert", "label": "Alert"},
    {"group": "elements", "url": "/elements/badge", "label": "Badge"},
    {"group": "elements", "url": "/elements/button", "label": "Button"},
    {"group": "elements", "url": "/elements/card", "label": "Card"},
    {"group": "elements", "url": "/elements/checkbox", "label": "Checkbox"},
    {"group": "elements", "url": "/elements/close", "label": "Close"},
    {"group": "elements", "url": "/elements/content", "label": "Content"},
    {"group": "elements", "url": "/elements/column", "label": "Column"},
    {"group": "elements", "url": "/elements/crumb", "label": "Crumb"},
    {"group": "elements", "url": "/elements/divider", "label": "Divider"},
    {"group": "elements", "url": "/elements/input", "label": "Input"},
    {"group": "elements", "url": "/elements/label", "label": "Label"},
    {"group": "elements", "url": "/elements/modal", "label": "Modal"},
    {"group": "elements", "url": "/elements/navlink", "label": "Navlink"},
    {"group": "elements", "url": "/elements/paragraph", "label": "Paragraph"},
    {"group": "elements", "url": "/elements/progress", "label": "Progress"},
    {"group": "elements", "url": "/elements/radio", "label": "Radio"},
    {"group": "elements", "url": "/elements/scrim", "label": "Scrim"},
    {"group": "elements", "url": "/elements/select", "label": "Select"},
    {"group": "elements", "url": "/elements/slider", "label": "Slider"},
    {"group": "elements", "url": "/elements/spinner", "label": "Spinner"},
    {"group": "elements", "url": "/elements/switch", "label": "Switch"},
    {"group": "elements", "url": "/elements/table", "label": "Table"},
    {"group": "elements", "url": "/elements/textarea", "label": "Textarea"},
    {"group": "elements", "url": "/elements/title", "label": "Title"},
    {"group": "elements", "url": "/elements/toggler", "label": "Toggler"},
    {"group": "presets", "url": "/presets/reboot", "label": "Reboot"},
    {"group": "presets", "url": "/presets/markup", "label": "Markup"},
    {"group": "presets", "url": "/presets/utilities", "label": "Utilities"},
    {"group": "presets", "url": "/presets/icons", "label": "Icons"},
    {"group": "guides", "url": "/guides/styles", "label": "Styles syntax"},
    {"group": "recipes", "url": "/recipes/features", "label": "Features"},
    {"group": "recipes", "url": "/recipes/footer", "label": "Footer"},
    {"group": "recipes", "url": "/recipes/hero-a1", "label": "Hero A1"},
    {"group": "recipes", "url": "/recipes/hero-a2", "label": "Hero A2"},
    {"group": "recipes", "url": "/recipes/navbar-a1", "label": "Navbar A1"},
    {"group": "recipes", "url": "/recipes/navbar-a2", "label": "Navbar A2"},
    {"group": "recipes", "url": "/recipes/navbar-a3", "label": "Navbar A3"},
    {"group": "recipes", "url": "/recipes/pricing", "label": "Pricing"},
    {"group": "recipes", "url": "/recipes/sign-in", "label": "Sign in"},
    {"group": "recipes", "url": "/recipes/tabs", "label": "Tabs"},
];
