name: Deploy

on:
  push:
    tags: ["*"]
  workflow_dispatch:
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.repository == 'jmjuanes/siimple' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - uses: actions/configure-pages@v5
      - run: yarn install
      - run: yarn run build
      - run: yarn run build:website
      - uses: actions/upload-pages-artifact@v4
        with:
          path: public
      - uses: actions/deploy-pages@v4
        id: deployment
