name: Deploy Playground App

on:
  release:
    types: [published]

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build siimple css
        run: npm run build

      - name: Install playground dependencies
        run: cd playground && npm install

      - name: Build playground
        run: npm run playground:build

      - name: Add configuration
        run: 'echo "$FIREBASE_CONFIG" > ./playground/.firebaserc'
        shell: bash
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG_PLAYGROUND }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "${{ secrets.FIREBASE_PROJECT }}"
          channelId: live
          target: playground
          entryPoint: playground
