name: Publish packages to NPM

on:
  release:
    types: [created]

jobs:
  packages:
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.folders.outputs.folders }}
    steps:
      - uses: actions/checkout@v5
      - id: folders
        run: echo "::set-output name=folders::$(ls -d packages/* | jq -R -s -c 'split("\n")[:-1]')"

  publish-packages:
    runs-on: ubuntu-20.04
    needs: [packages]
    strategy:
      matrix:
        package: ${{ fromJson(needs.packages.outputs.names) }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn release
      - run: cd ${{ matrix.package }} && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-main:
    runs-on: ubuntu-latest
    needs: [publish-packages]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn run build
      - run: yarn release
      - run: cd siimple && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: cd siimple-icons && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
